services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: renacer
      POSTGRES_PASSWORD: renacer
      POSTGRES_DB: renacer
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  dbdata:
